### ISSUE TITLE
Add syntax highlight in documentation deployment

### ISSUE THREAD

**Issue by dwikler** [dwikler/dcmspec#22]
See https://t.pxeger.com/mkdocs-material/reference/code-blocks/

poetry add --group docs pymdown-extensions

In mkdocs.yml:

```yaml
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      linenums_style: table
```
